kind: pipeline
name: default

trigger:
  event:
    exclude:
      - pull_request

steps:
- name: shellcheck
  image: koalaman/shellcheck-alpine
  pull: always
  commands:
    - shellcheck --version
    - for file in $(find ./root -type f); do echo $file; shellcheck $file; done;

- name: build
  image: plugins/docker
  pull: always
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: hotio/nzbhydra2
    auto_tag: true
    cache_from: "hotio/nzbhydra2"

- name: microbadger
  image: plugins/webhook
  pull: always
  settings:
    urls:
      - https://hooks.microbadger.com/images/hotio/nzbhydra2/M1eY_6Rb5Ap1bsS-nuUzsSzza1w=
